ESTADOS_CHOICES = (
    ('', 'Seleccione'),
    ('AG', 'Aguascalientes'),
    ('BC', 'Baja California'),
    ('BS', 'Baja California Sur'),
    ('CM', 'Campeche'),
    ('CS', 'Chiapas'),
    ('CH', 'Chihuahua'),
    ('CO', 'Coahuila'),
    ('CL', 'Colima'),
    ('DF', 'Ciudad de México'),
    ('DG', 'Durango'),
    ('GT', 'Guanajuato'),
    ('GR', 'Guerrero'),
    ('HG', 'Hidalgo'),
    ('JA', 'Jalisco'),
    ('MX', 'México'),
    ('MI', 'Michoacán'),
    ('MO', 'Morelos'),
    ('NA', 'Nayarit'),
    ('NL', 'Nuevo León'),
    ('OA', 'Oaxaca'),
    ('PU', 'Puebla'),
    ('QT', 'Querétaro'),
    ('QR', 'Quintana Roo'),
    ('SL', 'San Luis Potosí'),
    ('SI', 'Sinaloa'),
    ('SO', 'Sonora'),
    ('TB', 'Tabasco'),
    ('TM', 'Tamaulipas'),
    ('TL', 'Tlaxcala'),
    ('VE', 'Veracruz'),
    ('YU', 'Yucatán'),
    ('ZA', 'Zacatecas'),
)