# Generated by Django 4.2.1 on 2023-06-07 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Personas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("edad", models.IntegerField()),
                ("calle", models.CharField(max_length=100)),
                ("colonia", models.CharField(max_length=100)),
                ("codigo_postal", models.CharField(max_length=5)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Chihuahua", "Chihuahua"),
                            ("Jalisco", "Jalisco"),
                            ("Michoacan", "Michoacan"),
                        ],
                        max_length=100,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
